### ISSUE TITLE
Two errors: UnauthorizedAccessException and NullReferenceException

### ISSUE THREAD

**Issue by Moskus** [grocy/grocy-desktop#20] opened 2020-10-12 09:27 UTC
![image](https://user-images.githubusercontent.com/320826/95727884-17847700-0c7b-11eb-9e2a-4b26618d7b8c.png)

Just upgraded from 1.7.0 to 1.8.0. "nginx.exe" had several instances running. I got rid of those, and got this next:

![image](https://user-images.githubusercontent.com/320826/95728723-20c21380-0c7c-11eb-8c92-b772ccfd0b3f.png)

... and now I'm stuck. I've tried to repair the installation, but that didn't help.

**Comment by berrnd** [comment] 2020-10-12 10:03
Do you have any malware scanner running which may intercepts here?

Maybe check if something is wrong with `nginx.exe`, it should be located in `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\runtime-dependencies\1.8.0.0\nginx`.

You can also try to delete the whole `runtime-dependencies` folder there, will be recreated on the next application start.

**Comment by Moskus** [comment] 2020-10-12 10:21
Only Windows Defender, and it's not complaining.

The nginx folder seems fine, but running the nginx.exe gives the following error
' nginx: [emerg] bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions).

I'll try to delete the dependencies, and restart.

**Comment by Moskus** [comment] 2020-10-12 10:27
Deleting the `runtime-dependencies` folder gives the same `NullReferenceExcpetion` as before.

**Comment by berrnd** [comment] 2020-10-12 11:11
`An attempt was made to access a socket in a way forbidden by its access permissions`

Is maybe because you have enabled external access (?) (because it want to bind to `0.0.0.0` instead to `localhost`). Then you have to run grocy-desktop with admin privileges (Right click, "Run as administrator").

**Comment by Moskus** [comment] 2020-10-12 11:13
I do have external access enabled, but I don't have to run version 1.7 with higher privileges, and as stated, that works without problems.

But I'll give it a shot. :)

**Comment by Moskus** [comment] 2020-10-12 11:23
Starting version 1.8.0 with "Run as Administrator" still gives the same error...

**Comment by berrnd** [comment] 2020-10-12 11:58
I will do some more tests this evening, but nothing changed about the external dependencies, so strange...

Binding to an externally available port normally always requires admin privileges...

**Comment by Moskus** [comment] 2020-10-12 12:01
I've disabled UAC on this machine (which acts as a server, so no regular user input), so that might be it. But otherwise I've checked around, there's no set admin rights anywhere for 1.7 (which works).

**Comment by berrnd** [comment] 2020-10-12 13:10
The `NullReferenceException` is fixed in v1.8.1, sorry for that.

The other problem when starting `nginx.exe` I was unable to reproduce.
No "Run as admin"-privileges are required here (although I thought it is required - maybe only for non-admin users), just the normal Windows Firewall popup appears when starting first with "External access" enabled...

**Closed by berrnd** 2020-10-12 13:10 UTC
Labels: question

**Comment by Moskus** [comment] 2020-10-13 16:14
Version 1.8.1 works fine. 👍 
I'll now disable the automatic restart of grocy-desktop every night to see if it is fixed.
