### ISSUE TITLE
Can not create 2nd new product

### ISSUE THREAD

**Issue by kreisklasse** [grocy/grocy-desktop#6] opened 2019-04-28 08:36 UTC
Problem with adding new products.
My steps:
1. Starting grocy
2. "Purchase" - entering new barcode of new/unknown product
3. Create new product and save - everything ok
4. add 2nd new product via "Purchase" with barcode
5. Creat new product and try to save but following error message show up

![error_grocy1](https://user-images.githubusercontent.com/25295915/56861400-b7bfe080-69a0-11e9-987d-0d69433f6c6e.png)
![error_grocy2](https://user-images.githubusercontent.com/25295915/56861402-ba223a80-69a0-11e9-9667-78addd95681a.png)

but product does not exist, it's a new product.

6. Clicking on left menu list, grocy shows only white screen, no main screen anymore.
7. grocy has to be restarted to see main screen (grocy) again

My System: Windows 10 Home

**Comment by berrnd** [comment] 2019-04-28 10:27
We had a similar problem before, was reported to me by mail - the issue was that the PHP process exited for unknown reasons. Please check if there are any helpful messages from the PHP process (File/Show PHP server output).

**Comment by kreisklasse** [comment] 2019-04-28 10:31
for the time of the error, there is nothing in the Logs, sorry.
Log data ended always about 2-4 minutes prior.

**Comment by berrnd** [comment] 2019-04-28 10:35
Then it's probably the same problem...

I'll try to reproduce it, maybe the PHP integrated development webserver is not the best one and we should switch to a different approach...

**Comment by berrnd** [comment] 2019-04-28 11:21
I cannot reproduce it like you described it...

No solution for the origin problem, but I already added as a workaround that the PHP process is just restarted when it exited unintentionally in https://github.com/grocy/grocy-desktop/commit/60afe0a1e8fd086d1619aa7b6f6a62bcecca0d9e, however, that did not really work so far which i fixed right now...

Could you try to test if this helps as a workaround by replacing `grocy-desktop.exe` from the attached ZIP in `%localappdata%\grocy-desktop`?
[grocy-desktop.zip](https://github.com/grocy/grocy-desktop/files/3124897/grocy-desktop.zip)

**Comment by kreisklasse** [comment] 2019-04-28 11:37
Replaced the file, but on the first startup i got this error message.
After closing the message, grocy did not start up


log of this error message:
![grocy](https://user-images.githubusercontent.com/25295915/56863675-bf3fb380-69b9-11e9-998c-6506c6f928dd.png)

 bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   bei System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   bei GrocyDesktop.GrocyDesktopDependencyManager.<>c__DisplayClass5_0.<UnpackIncludedDependenciesIfNeeded>b__3()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GrocyDesktop.GrocyDesktopDependencyManager.<UnpackIncludedDependenciesIfNeeded>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GrocyDesktop.FrmMain.<FrmMain_Shown>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)



After restarting grocy 3 times (with the same error rom above) on the 4th restart it started up without error and i could add several new items without any error.

**Comment by kreisklasse** [comment] 2019-04-28 11:41
latest php log output:

https://hastebin.com/hekenibofu.md

**Comment by berrnd** [comment] 2019-04-28 11:42
The in the error message mentioned file should be there, so strange...

But thanks for testing, then let's try this as a workaround for now, will prepare a new version shortly...

**Comment by berrnd** [comment] 2019-04-28 11:50
New release is ready: https://github.com/grocy/grocy-desktop/releases/tag/v1.4.4

So closing this for now.

**Closed by berrnd** 2019-04-28 11:50 UTC
