### ISSUE TITLE
Bug: Bug on Windows Classic Install and Microsoft App

### ISSUE THREAD

**Issue by FancyNerd92** [grocy/grocy-desktop#42] opened 2023-01-22 02:49 UTC
I'm getting the error:

Windows 10 with (classic install)
InvalidOperationException
No process is associated with this object.

   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at GrocyDesktop.Management.PhpManager.Stop()
   at GrocyDesktop.FrmMain.FrmMain_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.Restart()
   at GrocyDesktop.FrmMain.ToolStripMenuItem_EnableBarcodeBuddy_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Same thing on Microsoft App:
ArgumentException
Item has already been added. Key in dictionary: 'PHP_FCGI_MAX_REQUESTS'  Key being added: 'PHP_FCGI_MAX_REQUESTS'

   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at GrocyDesktop.Management.PhpManager.Start()
   at GrocyDesktop.FrmMain.SetupPhpFastCgiServer()
   at GrocyDesktop.FrmMain.<FrmMain_Shown>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Any help?

**Comment by berrnd** [comment] 2023-01-22 07:55
Duplicate of #39, wasn't reproducible there, isn't reproducible by what you described above - I'll solve any bug which is reproducible, as always.

Maybe, just because that's more than often the underlying problem, you have fancy antimalware software running which blocks for example starting the integrated PHP server / `php.exe`.

**Closed by berrnd** 2023-01-22 07:55 UTC
Labels: invalid

**Comment by FancyNerd92** [comment] 2023-01-22 23:25
I don't have any antimalware or antivirus on my pc and i disable Windows Security at all. I install it right and when open it i'm getting this error one classic install and on app.

**Comment by berrnd** [comment] 2023-01-23 07:55
Then please describe each and every detail of your configuration / other installed software (would take a lot of time to recreate the complete environment that way, don't know if I will do it) or provide the complete environment in a virtual a machine or something.

Just what I said above: A problem needs to be reproducible, otherwise I can't fix it. I can't guess the problem by a single error message. "It doesn't work on my machine but I don't have provided any details about it at all" - would it possible for you to say anything about what the cause could be? I doubt it.
