### ISSUE TITLE
Updating Barcode Buddy breaks grocy-desktop

### ISSUE THREAD

**Issue by Pixouls** [grocy/grocy-desktop#45] opened 2023-06-02 15:47 UTC
Please bear with me as I am a noob.

I downloaded Grocy-desktop 2.3.1 on Win 11 on May 31st. This morning, I added three items. Then, an hour later. I got a 502 Bad Gateway error. I don't think I have changed anything or clicked anything special. 

nginx output is blank

php output is blank except for barcode buddy
[info] Starting socket server on [redacted]

barcode buddy is still visible (i haven't tried using it yet), just can't see anything on grocy

show browser developer tools outputs this:
**exception name**
NullReferenceException
**exception message**
Object reference not set to an instance of an object.
**exception stack trace**
   at GrocyDesktop.FrmMain.ToolStripMenuItem_ShowBrowserDeveloperTools_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Pixouls** [comment] 2023-06-02 15:48
Quick update: I had to enable external access and it comes back. Can someone explain why this might of happened, what external access is, and why it needs to be on?

**Comment by Pixouls** [comment] 2023-06-02 16:15
I think I'm getting some errors because the backups keep saving to my One Drive instead of saving locally. I didn't realize I did this. Even if I do a fresh install to save locally, the backups are trying to access files in one drive and thinks some files are missing. I'm not sure what their original file path is supposed to be. 

I scrapped the current installer. Downloaded it from the Microsoft Store. Page was blank.
Enabled external access. Page is back to normal. This leads me back to the question of why it needs to be on?

**Comment by berrnd** [comment] 2023-06-02 17:09
I can't say anything unless having some concrete error message or reproducible way to get an error - this is the tracker for reproducible bugs and features requests, not for general user support ([README ref](https://github.com/grocy/grocy-desktop#questions--help--bug-reports--feature-requests)).

Most of the time, generally and especially for grocy-desktop in the past, when weird things are going on, it was fancy antimalware software interfering - so first and always disable that stuff for reproducing problems. 

&nbsp;
> Please bear with me as I am a noob.

I'm always more than patient with everything, unless not reading README (which reads as READ THAT FIRST).

&nbsp;
> I think I'm getting some errors because the backups keep saving to my One Drive instead of saving locally.
> I'm not sure what their original file path is supposed to be.

Backups are only done when you do that, or when `Enable user data synchronization` is enabled (on closing grocy-desktop) and in that case that backup is also restored when starting grocy-desktop and I can imagine that maybe things go weird when the corresponding path cannot be accessed at that time. There is no default path for backups or for storing the "synchronized user data" (which is in fact just such a backup), you define that.

**Comment by Pixouls** [comment] 2023-06-02 17:29
Sorry, it is difficult for me to distinguish what might be a bug and what is usage support. I saw that there was a similar post in this section that someone else had (which at first, was the 502 bad gateway). I also searched the reddit for this topic but I didn't find any answers, but I do not have a reddit account to make a new post. The readme doesn't give me an idea of why external access would need to be on for my install to work. I do not have any special anti-malware software.

I started the Windows version and added three items again. I only enabled barcode buddy and enable external access. I never enabled user data sync.

When I open the windows version, I get this error pop up:
FileNotFoundException

Could not find file '[redacted]...\grocy-desktop\runtime-dependencies\2.3.1\barcodebuddy\config-dist.php'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GrocyDesktop.FrmMain.SetupBarcodeBuddy()
   at GrocyDesktop.FrmMain.<FrmMain_Shown>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Right now:
under "File", nothing is enabled, though the barcode buddy tab still shows up

the grocy change data location goes to a random games folder on my desktop (again, not something I chose), and creates an error when I try to change it because the games folder does not have access permissions. 

the barcode buddy change data location goes to my documents folder (I don't really want it there, but I wanted to see if I could get it out of my One Drive). When I try to move it into documents/grocy, it gives me that documents/my music does not have access permissions, even though that's not the folder I chose.

If I try to get any debug outputs, I only get a null reference exception.

Sorry that this is not reproducible enough. This appears to be all the error information that is given. I provide it should anyone else stumble upon the issue thread here and wonder what happened.

**Comment by berrnd** [comment] 2023-06-02 17:57
Again: I fix each and every bug, but I can't do that by not having something reproducible and only (really) weird reports of something. So it's useless to report anything more unless having that mentioned reproducible way.

&nbsp;
> Could not find file '[redacted]...\grocy-desktop\runtime-dependencies\2.3.1\barcodebuddy\config-dist.php'.

Can only guess once again that something is interfering on your machine. That file is part of Barcode Buddy's release ZIP which get unpacked to that path on the first start of grocy-desktop. If that's not there, something strange is happening.

&nbsp;
> the grocy change data location goes to a random games folder on my desktop (again, not something I chose.

Weird, once gain - grocy-desktop doesn't do that.

&nbsp;
> When I try to move it into documents/grocy, it gives me that documents/my music does not have access permissions, even though that's not the folder I chose.

More than weird, once again: grocy-desktop doesn't know anything about any folders on your machine. It simply opens a folder picker where you can choose one.

&nbsp;
> Sorry, it is difficult for me to distinguish what might be a bug and what is usage support. 

Generally pretty easy for everyone: Weird stuff only happening on your side and maybe only on a single machine is just like every time not a bug. Compare it with easy understandable real world non-software problems: When your car doesn't work, it's just like never a problem with the whole model line / a problem you report to the manufacturer.

**Comment by Pixouls** [comment] 2023-06-02 18:39
1. Download from Microsoft store
2. Open grocy, get 502 error
3. enable external access to get rid of 502 error. don't enable barcode buddy. turning it off will get 502 error again.
4. check where backups are saved. confirmed that they are not set to any specific folder. don't set any folder even by accident just x out.
5. add one test product and close out, app opens back up successfully
6. add another test product and add it to purchases and close out, app open back up successfuly
7. add more units, close, open, also successful
8. put computer to sleep and run again, close, open, success
9. add barcode scan to test product, close, open, success
10. turn on barcode buddy, close, open, success
11. click "update barcode buddy". error is thrown:
IOException
The process cannot access the file '...\runtime-dependencies\2.3.1\barcodebuddy' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at GrocyDesktop.Management.GrocyDesktopDependencyManager.<UpdateEmbeddedBarcodeBuddyRelease>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrocyDesktop.FrmMain.<ToolStripMenuItem_UpdateBarcodeBuddy_Click>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12. close and open. screen is blank. get error that config does not exist. go to "...runtime-dependencies\2.3.1\barcodebuddy". it's true, that folder is empty. (I think i did another close open, but I'm not sure).
13. click update barcode buddy again and get: null error. except now when i check the folder, the config file is there.
14. close and open. wow. looks like we survived. start up was successful.
15. try updating barcode buddy again. get error that it's being used by another process. look in the barcode folder, it's empty again. except for one stray folder.
16. try closing and opening it again. get the config is missing error again. 
17. Don't close and open yet. try updating barcode buddy again. get null error. barcode buddy folder is still missing config.
18. close and open. barcode buddy folder is back. starts up successfully. 

From this I determined:
- I still don't know why it's 502 on start up. Maybe it is a secret antimalware I don't realize is on.
- if you try to update barcode buddy, it will throw a processing error and empty the folder with the config file. If you try to close and open then update it again, then closing and opening it one more time should return the files in the folder.

**Comment by berrnd** [comment] 2023-06-02 19:01
#18 was about something, please read at least the title - it was about a problem when running grocy-desktop as "a server" / very long, which is not something grocy-desktop is supposed for.

Well, so reading through this whole life story once again, you first mentioned:
> _I downloaded Grocy-desktop 2.3.1 on Win 11 on May 31st. This morning, I added three items. Then, an hour later. I got a 502 Bad Gateway error. I don't think I have changed anything or clicked anything special._

Concludes to "haven't done anything".

Now you've mentioned:
> _click "update barcode buddy". error is thrown:_
> _[...]_

So turns out trying to update Barcode Buddy is the root cause for the problem, voila.

Now there is a reproducible way for a reproducible problem which will be fixed, as always - you really don't need to be software engineer to provide the necessary information at first. Much easier, much less time consuming.

**Comment by berrnd** [comment] 2023-06-02 19:07
- If it's a new installation without data: Reinstall, don't update Barcode Buddy.
- Delete the whole folder `C:\Users\<YOU>\.grocy-desktop\runtime-dependencies\2.3.1\barcodebuddy` (while grocy-desktop is not running) and again. Don't update Barcode Buddy (unless this here is fixed).

**Comment by berrnd** [comment] 2023-06-02 19:09
The problem about that "Enable external access" is required for anything is not reproducible and won't be tracked here -this here is about the reproducible problem caused by updating Barcode Buddy.

**Comment by Pixouls** [comment] 2023-06-02 19:35
I'm very sorry. I probably clicked on barcode buddy while trying to fix the 502 error.

**Closed** 2023-07-29 17:20 UTC
Labels: bug
