### ISSUE TITLE
[Feature Request] Portable Version (non-MSI)

### ISSUE THREAD

**Issue by OdinVex** [grocy/grocy-desktop#43] opened 2023-02-19 07:04 UTC
I see there's no Linux version, for those of us that don't want to pollute our Linux systems with an MSI-installation perhaps a portable version could be uploaded? Considering writing a cross-platform Qt-enabled version, little experience with Qt, though. Wondering if you might consider moving all of 'client' Grocy over to Flutter or Electron, they're cross-platform even for use with Android (maybe Apple stuff as well). One code-base, all platforms?

**Comment by berrnd** [comment] 2023-02-19 08:03
Duplicate of #37.

**Closed by berrnd** 2023-02-19 08:03 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2023-02-19 17:57
Seems that clicking a link and going on reading there is too much for a sunday, so of course I'm happy to help out - quoting myself from https://github.com/grocy/grocy-desktop/issues/37#issuecomment-1029127478 (about if Linux will be supported for grocy-desktop):

_No, not for grocy-desktop - would be technically also a whole other thing._

&nbsp;
> You could at least address the notions instead of dismissing without claiming duplicate.

Of course I will then go through every single word you mentioned - changes nothing, but well:

> I see there's no Linux version, for those of us that don't want to pollute our Linux systems with an MSI-installation perhaps a portable version could be uploaded?

A portable version will also not work on Linux in the very same way it doesn't currently.

This is a Windows desktop application wrapper for grocy with the goal to have a "just works" managed way to run grocy just like a normal Windows desktop application, for all users preferring that and maybe are not that tech savvy. It works well, since years.

Fun fact: The average target-audience user of grocy-desktop doesn't use Linux on their Desktop (source: reality).

> Considering writing a cross-platform Qt-enabled version
> Wondering if you might consider moving all of 'client' Grocy over to Flutter or Electron, they're cross-platform even for use with Android (maybe Apple stuff as well). One code-base, all platforms?

No, I don't consider that. grocy-desktop is not only the frontend (which is just a web browser), but also bundles and auto-manages the required PHP runtime and a webserver. This is never something which could be done in a platform agnostic way.

But of course you can build that. Share it, maybe grocy-desktop is then no longer needed, I have no problem with that, looking forward to it. The target for grocy-desktop won't change, everything else is just another project. And if you don't like the tech stack used, which is totally fine, just don't use it.

**Comment by berrnd** [comment] 2023-02-19 19:21
Once again: The goal of this project is to provide a managed "just works" experience to run grocy on Windows, like a regular Windows desktop application. Let us keep this finally in mind for everything else.

&nbsp;
> I was asking about a portable version of grocy-desktop
> This entire Issue thread was an inquiry of issue asking for a simple non-MSI.

A "managed just works"-way includes an managed installer, so also out of scope of this project.

&nbsp;
> or on Linux through Wine

You cannot, doesn't matter if it's "portable" or not. It has Windows only dependencies, just try stuff before speculating on it - a MSI can also be easily extracted, or just build everything yourself, the source is here.

&nbsp;
> I was only suggesting it is possible to rewrite the desktop version onto a cross-platform solution

I've never said that this is technically not possible, I've said that it's out of scope of this and just another project you're free to build.

&nbsp;
For your personal happiness, I've built such a "portable ZIP" just for you out of the latest release [v2.3.1](https://github.com/grocy/grocy-desktop/releases/tag/v2.3.1): ¯\\_(ツ)_/¯

https://nc.berrnd.org/s/t2zqgQ3aNLYM5ae

And just that we don't forget that here, since we tend to: It will not work on Linux.

**Comment by berrnd** [comment] 2023-02-19 19:25
It seems to me that you'd be able to run / install grocy just on a normal / regular webserver or simply use one of the available Docker images.

So I don't get why you bother with running it in that managed way at all - a managed way also has restrictions for those who maybe want to configure more or want to have control over every environment detail.

**Comment by Technetium1** [comment] 2023-02-19 20:03
@OdinVex I'm still not exactly grasping what the Docker version isn't able to provide for you…?

**Comment by berrnd** [comment] 2023-02-19 20:08
> but I'm guessing you've never heard of or maybe not have experienced things such as running from an external portable drive.

No, I have not - my knowledge on computers / IT and especially Windows is obviously somewhat extremely limited, sorry for that.

&nbsp;
> Pulling some magic to make the built-in nginx work (changed port from 4010 and 4011 due to permissions, using 32010 and 32011 at binary offsets 0x3848 and 0x3852 [...]

Sounds a lot easier than simply setting up a regular webserver, don't know why not everyone prefers it that way...

**Comment by Technetium1** [comment] 2023-02-19 20:18
> Just a lot of re-invention of the same wheels.

That is ironically the whole point that containerization aims to solve, to not reinvent wheels every time you want a specific unique dev environment. While I agree that it's definitely **not** a one-size-fits-all solution, this is exactly the kind of thing it excels at. If you do in fact have a home stack, it'd be ideal to experiment with containerization. There's nothing stopping you from specifying your data dirs being on any drive you want.

**Comment by berrnd** [comment] 2023-02-19 20:39
I guess we can continue this here endlessly, so why not:

&nbsp;
> Perhaps in the future, you could ask why someone might ask for a different format.

This here is a Feature Request for a project of mine. For my projects I naturally define the corresponding goals.

Both (Linux support and a portable version) is out of scope of this project / my defined goals. That's what I basically just said with my first reply. To be honest, the personal life story details behind each request most of the time is not something I'm interested in, since for what.


&nbsp;
> I'm a hold-over from older days when some DIY-ers kept 'database-like' software on portable drives (or thumb drives)

We have 2023, (secure) "internet facing" services are possible for everything everywhere.

That would mean you'd need to bring your laptop to Aldi to have your grocy shopping list at hand (and, at least here, they don't provide workstation, so the thumb drive way is not an option - but I could be wrong, my limited computer experience and so on you know...).

That's why I (and kind of every not only grocy user) uses / installs an app like that just like any other web app on their "internet facing" (and when it's behind a VPN or whatever for enhanced security) server to have grocy / the corresponding app / data just at hand when needed - so everywhere, since we have 2023 (and I say that while living in Germany, the homeland of Funkloch).
