### ISSUE TITLE
"Screen" barcode buddy screen is not working for Grocy desktop (Websocket server is not running)

### ISSUE THREAD

**Issue by bluckholl** [grocy/grocy-desktop#40] opened 2022-12-31 12:47 UTC
Hi,
I have installed Grocy desktop 2.3.1,
All is working except "Screen" screen that shows "Error 10061: No connection could be made because the target machine actively refused it".
In the settings it says "Websocket server is not running! No connection could be made because the target machine actively refused it"

How can I fix it?

Thanks!

![image](https://user-images.githubusercontent.com/2509820/210137166-87b14cbf-a189-425e-bf29-281340de22b4.png)

* I understood this is not a barcode buddy issue - as commented here: 
https://github.com/Forceu/barcodebuddy/issues/205

**Comment by berrnd** [comment] 2022-12-31 13:09
Can't reproduce it:
- Fresh installation of v2.3.1 on a up to date Windows 10 machine
- Enabled Barcode Buddy
- Clicked on "Screen" in the top right corner

=> Looks like that:
![grafik](https://user-images.githubusercontent.com/2161815/210137646-e124cd27-39c2-4154-9b32-7a8f11eaa972.png)

So, as also already mentioned on the issue template, the exact steps, environment information and everything else needed to reproduce that are required, if something should be fixed.

More than often something like that is caused by fancy antimalware software that interferes with network stuff, so maybe triple check that, e.g. by temporarily disabling such things.

In the help menu there are also options to show the PHP runtime and webserver output, maybe something pops up there.

**Closed by berrnd** 2022-12-31 13:09 UTC
Labels: invalid

**Comment by bluckholl** [comment] 2022-12-31 21:14
Hi,
I tried to reproduce but I see that after PC restart it started to work..
Thanks for the quick response and sorry for this false report.
